package com.example.timeboxvibe.ui.main

/**
 * Localization strings ported from i18n.js.
 * Supports English, Chinese (Simplified), and Japanese.
 */
data class AppStrings(
    val title: String,
    val focusMode: String,
    val breakMode: String,
    val timer: String,
    val templates: String,
    val entropy: String,
    val start: String,
    val pause: String,
    val reset: String,
    val skip: String,
    val ticks: String,
    val vibe: String,
    val on: String,
    val off: String,
    val presetsTitle: String,
    val addCustom: String,
    val cancel: String,
    val focusThemePlaceholder: String,
    val sessionLimit: String,
    val step: String,
    val of: String,
    val block: String,
    val entropyBomb: String,
    val entropyDesc: String,
    val addTaskPlaceholder: String,
    val addButton: String,
    val explodeButton: String,
    val detonatingButton: String,
    val missionLabel: String,
    val launchEmergency: String,
    val alarmSoundLabel: String,
    val volumeLabel: String,
    val showSettings: String,
    val hideSettings: String,
    val themeLabel: String,
    val defaultTasks: List<String>,
    
    // Custom presets strings
    val presetNameLabel: String,
    val presetNamePlaceholder: String,
    val engineStyleLabel: String,
    val durationLabel: String,
    val minutes: String,
    val seconds: String,
    val bigBoxLabel: String,
    val smallLoopLabel: String,
    val sequenceLabel: String,
    val sequencePlaceholder: String,
    val unitLabel: String,
    val saveTemplate: String,
    val completionBehaviorLabel: String,
    val requireDismissalLabel: String,
    val autoProgressLabel: String,
    val classicBehaviorDesc: String,
    val dualBehaviorDesc: String,
    val dual5BehaviorDesc: String,
    val sequenceBehaviorDesc: String,
    val dualSequenceBehaviorDesc: String
)

fun getStrings(lang: String): AppStrings = when (lang) {
    "zh" -> AppStrings(
        title = "时光律动",
        focusMode = "专注模式",
        breakMode = "放松洗脑",
        timer = "计时器",
        templates = "时间模板",
        entropy = "任务炸弹",
        start = "开始",
        pause = "暂停",
        reset = "重置",
        skip = "跳过",
        ticks = "滴答",
        vibe = "振动",
        on = "开",
        off = "关",
        presetsTitle = "时间箱模板",
        addCustom = "自定义",
        cancel = "取消",
        focusThemePlaceholder = "现在要专注做什么？",
        sessionLimit = "总倒计时",
        step = "当前第",
        of = "步 / 共",
        block = "步",
        entropyBomb = "无序任务炸弹",
        entropyDesc = "被各种繁琐事情卡住了？在下面输入待办小任务，点击【引爆】，让随机律动帮你迈出第一步！",
        addTaskPlaceholder = "输入一件超简单、极低门槛的小事...",
        addButton = "添加",
        explodeButton = "引爆 / 随机挑选",
        detonatingButton = "正在引爆...",
        missionLabel = "恭喜！你的专属任务已锁定：",
        launchEmergency = "开启 90秒冲刺并立刻执行！",
        alarmSoundLabel = "闹钟铃声",
        volumeLabel = "铃声音量",
        showSettings = "系统设置",
        hideSettings = "关闭设置",
        themeLabel = "界面配色主题",
        defaultTasks = listOf("整理书桌或工作台", "写出一句论文或工作文案", "去洗 3 个碗", "回复或归档 1 封邮件", "站起来拉伸或走动 60秒"),
        
        presetNameLabel = "模板名称",
        presetNamePlaceholder = "例如：我的复习螺旋",
        engineStyleLabel = "计时器机制",
        durationLabel = "持续时长",
        minutes = "分钟",
        seconds = "秒",
        bigBoxLabel = "大时间箱 (总时长)",
        smallLoopLabel = "小动作循环",
        sequenceLabel = "时间序列 (用英文逗号分隔数字)",
        sequencePlaceholder = "例如：10, 8, 6, 4, 2",
        unitLabel = "数字单位",
        saveTemplate = "保存模板",
        completionBehaviorLabel = "完成行为",
        requireDismissalLabel = "需要手动消除 (闹钟)",
        autoProgressLabel = "自动进行下阶段",
        classicBehaviorDesc = "应用于单次倒计时。",
        dualBehaviorDesc = "应用于小动作循环。大时间箱（总时长）在结束时总是会响铃。",
        dual5BehaviorDesc = "应用于中等循环。大时间箱（总时长）在结束时总是会响铃，微观秒表自动循环。",
        sequenceBehaviorDesc = "应用于步骤之间的过渡阶段。最后一个步骤结束时总是会响铃。",
        dualSequenceBehaviorDesc = "应用于大块之间的过渡阶段。小动作循环自动循环，最后一个大块结束时总是会响铃。"
    )
    "ja" -> AppStrings(
        title = "タイムボックス",
        focusMode = "集中モード",
        breakMode = "リラックス中",
        timer = "タイマー",
        templates = "テンプレート",
        entropy = "ランダム選択",
        start = "スタート",
        pause = "一時停止",
        reset = "リセット",
        skip = "スキップ",
        ticks = "秒針音",
        vibe = "バイブ",
        on = "オン",
        off = "オフ",
        presetsTitle = "テンプレート",
        addCustom = "新規作成",
        cancel = "キャンセル",
        focusThemePlaceholder = "何に集中しますか？",
        sessionLimit = "セッション全体",
        step = "ステップ",
        of = " / 全",
        block = "段階",
        entropyBomb = "エントロピー爆弾",
        entropyDesc = "何をすべきか迷って動けなくなっていませんか？ タスクを書き出し、【爆破】ボタンを押してランダムに1つ選びましょう！",
        addTaskPlaceholder = "すぐ終わる簡単なタスクを入力...",
        addButton = "追加",
        explodeButton = "爆破する / 1つ選ぶ",
        detonatingButton = "爆破中...",
        missionLabel = "あなたのミッションはこちらです：",
        launchEmergency = "90秒タイマーを起動して开始！",
        alarmSoundLabel = "アラーム音設定",
        volumeLabel = "アラーム音量",
        showSettings = "アプリ設定",
        hideSettings = "設定を閉じる",
        themeLabel = "カラーテーマ",
        defaultTasks = listOf("机の上を片付ける", "文章を1行書く", "お皿を3枚洗う", "メールを1通整理する", "立ち上がって60秒間ストレッチする"),
        
        presetNameLabel = "テンプレート名",
        presetNamePlaceholder = "例: 集中スパイラル",
        engineStyleLabel = "タイマーの種類",
        durationLabel = "時間設定",
        minutes = "分",
        seconds = "秒",
        bigBoxLabel = "大タイマー (全体の制限時間)",
        smallLoopLabel = "小タイマー (行動ループ秒数)",
        sequenceLabel = "スパイラル時間設定 (カンマ区切りの数字)",
        sequencePlaceholder = "例: 10, 8, 6, 4, 2",
        unitLabel = "数値の単位",
        saveTemplate = "保存する",
        completionBehaviorLabel = "完了時の動作",
        requireDismissalLabel = "手動停止が必要 (アラーム)",
        autoProgressLabel = "自動移行",
        classicBehaviorDesc = "単一のカウントダウンに適用されます。",
        dualBehaviorDesc = "小タイマー（行動ループ）に適用されます。大タイマー（全体の制限時間）終了時は常にアラームが鳴ります。",
        dual5BehaviorDesc = "中間アラームループに適用されます。大タイマー終了時は常にアラームが鳴り、秒針ループは常に自動移行します。",
        sequenceBehaviorDesc = "途中の各ステップに適用されます。最後のステップ終了時は常にアラームが鳴ります。",
        dualSequenceBehaviorDesc = "途中の各大タイマーブロックに適用されます。行動ループは常に自動移行し、最後のブロック終了時は常にアラームが鳴ります。"
    )
    else -> AppStrings(
        title = "TimeBox Vibe",
        focusMode = "Focus Mode",
        breakMode = "Unwinding",
        timer = "Timer",
        templates = "Templates",
        entropy = "Entropy",
        start = "Start",
        pause = "Pause",
        reset = "Reset",
        skip = "Skip",
        ticks = "Ticks",
        vibe = "Vibe",
        on = "On",
        off = "Off",
        presetsTitle = "Templates",
        addCustom = "Custom",
        cancel = "Cancel",
        focusThemePlaceholder = "What are you focusing on?",
        sessionLimit = "Session Limit",
        step = "Step",
        of = "of",
        block = "Block",
        entropyBomb = "Entropy Bomb",
        entropyDesc = "Stuck in analysis paralysis? Enter your tasks below, click EXPLODE, and let entropy pick what to start now!",
        addTaskPlaceholder = "Enter a small, low-effort task...",
        addButton = "Add",
        explodeButton = "Explode / Pick Random",
        detonatingButton = "Detonating...",
        missionLabel = "Your Mission, Should You Choose To Accept:",
        launchEmergency = "Launch 90s Box & Do It!",
        alarmSoundLabel = "Alarm Sound",
        volumeLabel = "Volume",
        showSettings = "Settings",
        hideSettings = "Close Settings",
        themeLabel = "Interface Theme",
        defaultTasks = listOf("Tidy up workspace", "Write 1 sentence", "Wash 3 dishes", "File 1 email", "Stretch / walk for 60s"),
        
        presetNameLabel = "Preset Name",
        presetNamePlaceholder = "e.g. My Study Spiral",
        engineStyleLabel = "Engine Style",
        durationLabel = "Duration",
        minutes = "Minutes",
        seconds = "Seconds",
        bigBoxLabel = "Big Box (Overall)",
        smallLoopLabel = "Small Action Loop",
        sequenceLabel = "Interval Sequence (comma-separated numbers)",
        sequencePlaceholder = "e.g. 10, 8, 6, 4, 2",
        unitLabel = "Unit of Numbers",
        saveTemplate = "Save Template",
        completionBehaviorLabel = "Completion Behavior",
        requireDismissalLabel = "Require Dismissal (Alarm)",
        autoProgressLabel = "Auto-Progress",
        classicBehaviorDesc = "Applies to the singular countdown.",
        dualBehaviorDesc = "Applies to the Small Action Loop. The Big Box (Overall) always alarms at the end.",
        dual5BehaviorDesc = "Applies to the Medium Alarm Loop. The Macro Block (Big) always alarms at the end. Micro stopwatch loop always auto-progresses.",
        sequenceBehaviorDesc = "Applies to intermediate steps. The final step always alarms at the end.",
        dualSequenceBehaviorDesc = "Applies to intermediate big blocks. Small action loop always auto-progresses, and the final block always alarms at the end."
    )
}
